/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp2;

//import controler.ProjectController;
//import model.Task;
//import model.Project;
//import java.sql.Connection;
//import java.util.List;
//import model.Project;
//import util.ConnectionFactory;

public class Main {
 
    //public static void main(String[] args) {
   // Connection c = ConnectionFactory.getConnection();
   
   // ProjectController projectController = new ProjectController();
    
   // Project project = new Project();
   // project.setName("Novo nome");
   // project.setDescription("description");
   // projectController.save(project);
    
   // project.setName("Novo nome do projeto");
   // projectController.update(project);
   
   // List<Project>projects = projectController.getAll();
   // System.out.println("Total de projetos: "+ projects.size());
   // ConnectionFactory.closeConnection(c);

//TaskController taskController = new TaskController();
//
//Task task = new Task();
//task.setIdProject();
//task.setName("Projetinho");
//task.setDescription("Todo app 100% atualizado");
//task.setNotes("Estudar JAVA");
//task.setIsCompleted(false);
//
//taskController.save(task);

    }

